#----------------------------------------------------------------------------------------------------
# Configuration file for CustomCommands.
#----------------------------------------------------------------------------------------------------

# Locale

locale: customcommands_en_US.yml
